[pytest]
testpaths =
    tests
    api_tests
python_files = test_*.py
python_functions = test_*
pythonpath = .
base_url = https://www.saucedemo.com

addopts =
    -v
    --tracing=retain-on-failure
    --screenshot=only-on-failure
    --video=retain-on-failure
    --alluredir=allure-results

markers =
    flaky: retries for unstable tests